version: "3.7"

services:
  postgres:
    container_name: boiler-pg
    image: mdillon/postgis:11
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=boiler

  main:
    container_name: boiler-server
    build:
      context: ./
      args:
        NPM_TOKEN: $NPM_TOKEN
      target: development
    volumes:
      - ./src:/app/src
      - /src/node_modules
    ports:
      - 9821:9821
    command: npm run start:dev
    links:
      - postgres
